// Reads all module README.md and quiz.json files and generates a static
// TypeScript data file so no filesystem access is needed at runtime.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const modulesDir = path.resolve(__dirname, '..', '..', 'modules');
const outFile = path.resolve(__dirname, '..', 'src', 'lib', 'module-data.generated.ts');

const slugs = [
  '01-docker', '02-aws-foundations', '03-aws-sa-associate', '04-terraform',
  '05-kubernetes', '06-ci-cd-pipelines', '07-monitoring-observability',
  '08-system-design', '09-interview-prep', '10-ai-for-cloud-devops',
];

const data = {};

for (const slug of slugs) {
  const readmePath = path.join(modulesDir, slug, 'README.md');
  const quizPath = path.join(modulesDir, slug, 'tests', 'quiz.json');

  data[slug] = {
    markdown: fs.existsSync(readmePath) ? fs.readFileSync(readmePath, 'utf-8') : '',
    quiz: fs.existsSync(quizPath) ? JSON.parse(fs.readFileSync(quizPath, 'utf-8')) : [],
  };
}

const tsContent = `// AUTO-GENERATED by scripts/prebuild.mjs — do not edit manually
export const MODULE_DATA: Record<string, { markdown: string; quiz: any[] }> = ${JSON.stringify(data, null, 2)};
`;

fs.writeFileSync(outFile, tsContent, 'utf-8');
console.log(`Generated ${outFile} with ${slugs.length} modules`);
